version: "3.7"

services:
  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: easyhealth
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test123
    ports:
     - "5432:5432"
    volumes:
     - data:/var/lib/postgresql/data

  goapp:
    build:
      context: .
      dockerfile: Dockerfile
    image: my-go-app
    ports:
      - "8080:8080"
    
    depends_on:
      - database
    networks:
      - default
  volumes:
    data:
    
